#!/bin/sh -e

# Yes this is ugly, but there doesn't seem to be a better way to get yarn to
# output the current version of the package.
git tag $(yarn version < /dev/null | grep 'Current version' | cut -d: -f2)
