version: 2.1

references:
  filter-tags: &filter-tags
    filters:
      branches:
        ignore: /.*/
      tags:
        only: /^\d*\.\d*\.\d*/


jobs:
  build:
    docker:
      - image: circleci/python:3.5-node
    steps:
      - checkout

      - run: &js-deps
          name: Install JavaScript requirements
          command: yarn

      - run: &python-deps
          name: Install Python requirements
          command: ./pythonFiles/install-requirements.sh

      - run:
          name: Build
          command: |
            yarn run package

  release:
    docker:
      - image: circleci/python:3.5-node
    steps:
      - checkout

      - run: *js-deps
      - run: *python-deps

      - run:
          name: Build & Publish
          command: |
            echo '{"publishers":[{"name":"peterjclaw","pat":"$AZURE_TOKEN"}]}' > ~/.vsce
            ./script/release/release


workflows:
  version: 2.1

  build:
    jobs:
      - build

  release:
    jobs:
      - release:
          <<: *filter-tags
