version: 2.1

references:
  filter-tags: &filter-tags
    filters:
      branches:
        ignore: /.*/
      tags:
        only: /^\d*\.\d*\.\d*/


jobs:
  build:
    docker:
      # TODO(upgrade): un-pin cheerio once we have newer NodeJS
      - image: cimg/python:3.7-node
    steps:
      - checkout

      - run: &js-deps
          name: Install JavaScript requirements
          command: yarn

      - run: &python-deps
          name: Install Python requirements
          command: ./pythonFiles/install-requirements.sh

      - run:
          name: Build
          command: |
            yarn run package

  release:
    docker:
      - image: cimg/python:3.7-node
    steps:
      - checkout

      - run: *js-deps
      - run: *python-deps

      - run:
          name: Build & Publish
          command: |
            export VSCE_PAT=$AZURE_TOKEN
            ./script/release/release


workflows:
  version: 2.1

  build:
    jobs:
      - build

  release:
    jobs:
      - release:
          <<: *filter-tags
